# Generated by Django 2.2.4 on 2019-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano',
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
