# Generated by Django 2.2.4 on 2019-11-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_auto_20191124_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Lido'), (1, 'Estou lendo'), (2, 'Parei de ler'), (3, 'Quero ler')], default=0),
        ),
    ]
